### ISSUE TITLE
Screen freeze when swipe back 

### ISSUE THREAD

**Issue by SanjithKanagavel** [jonkykong/SideMenu#129]
I could add the left and right menu. But I can't swipe back to main controller. The UI gets freezes up.  iOS 10.2 + xcode 8.2.1. Please check.  I am try in code style.

**Comment by jonkykong** [comment]
Closed for failing to complete the new issue checklist.

**Comment by SanjithKanagavel** [comment]
I have completed the new checklist. Please check.

**Comment by jonkykong** [comment]
You could not have tried the demo project since you are not using storyboard. 

There are a lot of reasons why this may not be working for you as you have provided very little information.

For me to follow up, you should create a new project that reproduces the problem and share a link with me to observe.
