### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by balazsgerlei** [jonkykong/SideMenu#154]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Please when you relase a new version, provide a chagelog/release notes with the most important changes and breaking changes (if there is any) at least. It would be the best to add these into "Releases" section of the Github page or by adding a "CHANGELOG.md". Thanks!

**Comment by jonkykong** [comment]
@balazsgerlei I'll note this for the future.

For what it's worth, each new release has been a dot build with the exception of Swift 2.3 -> 3, meaning that there's non-breaking changes. There have been some API deprecations but the compiler should help identify those and make the appropriate recommendations. What is the specific problem you encountered where this would have helped you?

**Comment by balazsgerlei** [comment]
Hi!
No, no specific problem yet (I am yet to update to the latest version though), just when we are preparing to update the dependencies of our projects, we usually go through the changelogs first to see if there are any pontential problem. I'm happy to hear that there were no breaking changes recently. I am currently going through one of this dependency update and every libraries we use have changelogs except this one and I would not like to go through individual commit messages to see if there is any potential problem. So a changelog would be a nice addition later, for now I will just update to the latest version and hopefully as you said, there is nothing that could extensively break existing code.

**Comment by oleghnidets** [comment]
+1. I also look at changelog after updating Pods.

**Comment by jonkykong** [comment]
Gentlemen: full disclosure, while I agree that providing a change log is a best practice, I'm resisting doing it because it's going to add more time to maintaining this library which is already taking a considerable amount of time. If you must see the details, check out the commit notes as a backup. I also make sure update the code in a way that doesn't break older implementations, but if I must, I have built in deprecation warnings so that Xcode will guide you on any breaking changes.

Alternatively, you can specify the version of the library you use in your podfile. If you decide to update SideMenu and discover issues, simply return to the previously working version.

**Comment by oleghnidets** [comment]
Just wanted to let you know that changelog can be important for some devs. 
I do respect your work.  Don't take me wrong, I know and understand that maintaining a library is a big deal. 
Anyway, thanks for the library ;]
