### ISSUE TITLE
Passing Data

### ISSUE THREAD

**Issue by mceraso** [jonkykong/SideMenu#20]
Hi jonkykong,

Do you have documentation on how to pass data between the SideMenu and the MainView?

**Comment by jonkykong** [comment]
Hi @mceraso, so I think the implementation I built for was to have a generic menu view that was context independent -- meaning, it didn't care where it was showed from, it just showed the same menu.

That said, there are a couple of ways you could do this.

First, is from whichever viewController you want to display a certain type of side menu, you change the left or right menu when that viewController appears (and possibly set them back to what they were before when you dismiss it).

Second, since the implementation uses standard presentation methods, like `presentViewController` to be displayed, you can treat it like you would any other pair of viewControllers to pass data back and forth. So try making use of `presentingViewController` or setting up delegates when the menu appears.

**Comment by mceraso** [comment]
@mgonzales7, does this help?

**Comment by hardikamal** [comment]
@mceraso @mgonzales7 Any solution found to this issue?
