### ISSUE TITLE
My SideMenu don´t work

### ISSUE THREAD

**Issue by jose46moreno** [jonkykong/SideMenu#205]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

It is difficult to describe in words, i would like to be able to send my simple project for you see the issue.

**Comment by jonkykong** [comment]
Please use pictures and words. I don't have time to look at everyone's projects.

**Comment by jose46moreno** [comment]
This is a simple structure of my interfaces. One VC to register and then, the main interface is a tabBar. The other interfaces are VC embed in a navigationController.
I put a UIBarButtonItem in the view to hide the back button and so i can present the SideMenu. 
But i have a problem with the tabBar, when i select the first row of tableViewMenu, i go to the tabBar but the backButton appears again and i switch to the secondView of tabBar the backButton disappears but when i present the SideMenu and i select again the first row, i go to the first view of tabBar with the backButton appears and the second tabBarItem selected.

<img width="1440" alt="captura de pantalla 2017-06-03 a las 10 43 22" src="https://cloud.githubusercontent.com/assets/8105593/26752167/3e107142-484a-11e7-96ad-bb1b6ac58adc.png">

I hope you can help me.

**Comment by xxtesaxx** [comment]
SideMenu will replace the content of a UINavigationController with the new ViewController. That might be the missing key in your app. Your UITabBarController is not embedded in a UINavigationController which could cause the problems. Can you try putting it in a navigation controller (you probably need to hide the navigation bar of the controller since each tab has it's own navigation controller)

<img width="720" alt="bildschirmfoto 2017-06-03 um 09 11 37" src="https://cloud.githubusercontent.com/assets/3000808/26753811/bf6ba706-483c-11e7-8999-2092c4bb4ca7.png">

**Comment by jonkykong** [comment]
You need to read the README and look at the `menuPresentMode` property.

**Comment by jose46moreno** [comment]
What a kindness.
I'll look for something better.

Thanks.
