### ISSUE TITLE
Black page controller background on the bottom

### ISSUE THREAD

**Issue by NikKovIos** [jonkykong/SideMenu#206]
![simulator screen shot 3 2017 11 53 29](https://cloud.githubusercontent.com/assets/16647690/26752215/5708bbc4-4853-11e7-9974-c066c18a973e.png)

    SideMenuManager.menuFadeStatusBar = false
    SideMenuManager.menuAnimationBackgroundColor = UIColor.clear

It can be not a bug, but the page controller's behaviour, because i implement it in `UIPageViewController` by `func presentationIndex(for pageViewController: UIPageViewController) -> Int`. In that case - that issue just to note ;)

**Comment by xxtesaxx** [comment]
How is one supposed to help you when you provide so less information. We won't guess what you are trying to do or how your code looks like. Do you really expect someone to spend time on trying to figure out your problem and provide you a solution? If you are really looking for help, provide as much detail as possible. Include screenshots of your storyboard, code samples and describe what exactly the problem is.

**Comment by jonkykong** [comment]
@NikKovIos all you've stated is "it" can not be a bug without saying what "it" is. Please provide more information.

**Comment by NikKovIos** [comment]
Look, there is already anouth information to reproduce that bug.

Ok,i can tell obvious addition info:
1) There is a UIPageViewController with method, i've wrote above. 
2) Its 4 View Controllers in it. (no matter how much) 
3) Storyboard looks like:
FirstVC -(present modally segue)-SideNavigationVC-(rootSegue)-PageController. Pages filled programmatically of course.

**Comment by xxtesaxx** [comment]
Seriously @NikKovIos? Nothing obvious. Theres a lot one could need to reproduce. Keep in mind that you are getting this awesome piece of software for free. Nobody here is paid for support. About your problem, I spent 10 seconds on google and I think this is not a bug of SideMenu rather than a simple wrong configuration of your page controller. 

https://stackoverflow.com/questions/28077869/uipageviewcontroller-displaying-a-black-bar
https://stackoverflow.com/questions/17779735/how-do-i-make-the-bottom-bar-with-dots-of-a-uipageviewcontroller-translucent
https://stackoverflow.com/questions/19935887/how-to-remove-the-bottom-gap-of-uipageviewcontroller

**Comment by jonkykong** [comment]
@NikKovIos You still haven't stated what the bug is. Is it that you cannot swipe on the page view controller? Is it that there's a black bar? What is the problem?

**Comment by NikKovIos** [comment]
I think @xxtesaxx brought the answer. Thanks!
