### ISSUE TITLE
I don't know why I am getting this error "SideMenu Warning: attempt to push a View Controller from nil where its navigationController == nil. It must be embedded in a Navigation Controller for this to work."  

### ISSUE THREAD

**Issue by kishor010** [jonkykong/SideMenu#238]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by kishor010** [comment]
I am getting this warning "SideMenu Warning: attempt to push a View Controller from nil where its navigationController == nil. It must be embedded in a Navigation Controller for this to work."
I like Sidemenu but I am using it like How you give the Usage. 
But I have to for another view controller which is my child view. But I am getting this above warning. 
I saw same issue in issue List but didn't get clearly. I read everything. 
Please help me. Thanks

**Comment by jonkykong** [comment]
Please follow the README carefully.

**Comment by sibblegp** [comment]
You are very condescending and not very helpful.  A lot of people ask this question and you never give the answer.  I've read the README a dozen times and cannot seem to find an answer.  Why not just give it?

**Comment by jonkykong** [comment]
@sibblegp:

- I have spent weeks providing a completely free library with no expectation of compensation.
- I have spent hours putting together a thorough README to help people understand how it's used.
- I have added logging to explain the problem being encountered in this issue to help developers fix it.
- I even said **please**.

Despite everything I've given so far, you expect me to spend even _more_ of my time answering every question asked of me (often due to inexperience or impatience)? You may want to re-evaluate  who's being condescending here.

**Comment by sibblegp** [comment]
You've made a very successful open source project and are using it to promote your paid services.  We are currently looking to hire someone to make our iOS app.  Your attitude about helping people with your open source projects has made sure I'd never hire you and I'll make sure no one else I know ever hires you either.

Open source is about giving of your time freely.  I'm a very experienced developer, had this exact problem, and found no help in the readme and after hours of frustration uninstalled your solution and went looking for others, considering that I knew I could find no support here (I had other issues as well).  Considering there are about a half dozen support requests for this same issue, telling them all to read the readme is a terrible solution.  And just because they are inexperienced devs doesn't make them unworthy of receiving support.  In fact, that makes them the most worthy.  It's our job as experienced developers to help those who are new and struggling.

It's your elitist attitude that drives people from this profession when they are just learning.  I'm certainly glad you don't manage anyone.

**Comment by jonkykong** [comment]
@sibblegp we have a difference of philosophy. I respect yours, and I ask you to respect mine.

I currently teach several beginners how to code. I advocate motivating them to think for themselves and learn how to troubleshoot things rather than teaching them dependence on someone with more experience to get fast answers (and promptly forgetting those answers). Everyone I have taught has found this to be very helpful. Either approach to teaching has its pros and cons.

If you read through all of the issues, you'll see that I've answered multiple requests for help that were thoughtfully investigated, so this is by no means a carte-blanche approach to shutting down issues. I don't have the cycles to teach every new developer how to code, so I triage the requests by asking for them to supply some of the investigation themselves, as is a good practice every aspiring developer should learn.

Specific to your question at stake, the answer is literally in the warning:

> SideMenu Warning: attempt to push a View Controller from nil where its navigationController == nil. It must be embedded in a Navigation Controller for this to work.

I cannot be any clearer on this, so answering issues opened about it will mean I am repeating myself. This is lost time. You are free to use this or any other library you think is best for your project.

A big part of the open source community is also about civility. I invite you to keep it civil in line with the [Code of Conduct](https://github.com/jonkykong/SideMenu/blob/master/CODE_OF_CONDUCT.md). I have not insulted you. You have called me condescending, elitist, insinuated I'm bad at management, and stated you'd never hire me -- all because you're dissatisfied with getting help on a free library. Meanwhile, over 1600+ people have starred this library and several others have contributed to it. Based on the evidence your perspective may be out of alignment.
