### ISSUE TITLE
 SideMenu transit to left side when keyboard tool bar tap

### ISSUE THREAD

**Issue by BoshiLee** [jonkykong/SideMenu#257]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

SideMenu worked fine when present and dismiss.

However, I have occurred wired problem when I tap keyboard toolbar the side menu will transit from right to left.

Why will this problem show up? Did I missing code to implement?

`
func loadSideMenu() {
// Define the menus

guard let sideMenuVC = ViewController.gigSearch.instantiate() as? GigSearchSideMenuController else {return}
let menuRightNavigationController = UISideMenuNavigationController(rootViewController: sideMenuVC)
menuRightNavigationController.navigationBar.isHidden = true
SideMenuManager.menuPresentMode = .menuSlideIn
SideMenuManager.menuRightNavigationController = menuRightNavigationController
menuRightNavigationController.leftSide = false
SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
`

![sep-11-2017 23-45-29](https://user-images.githubusercontent.com/20209263/30284650-22aee24a-96e1-11e7-9403-68ce69af579f.gif)

**Comment by jonkykong** [comment]
@BoshiLee I don't know exactly what the issue is, but chances are the keyboard is modifying the layout as part of its reveal functionality. You would need to do more debugging to ensure that SideMenu's layout code isn't being erroneously triggered vs. the keyboard modifying the layout.

You're the first to report this problem as it looks like you're using SideMenu as a text input form. From a UI perspective, doing this is atypical, and since my time is extremely limited I won't be able to fix this problem.

If you would like to continue researching the issue, I'm happy to provide any feedback I can along the way. If an appropriate fix can be found then I would encourage you to contribute to this repository through a pull request.
