### ISSUE TITLE
SideMenu Warning: menuAddScreenEdgePanGesturesToPresent for the right side was called before menuRightNavigationController has been defined. The gesture will not work without a menu.

### ISSUE THREAD

**Issue by hemangshah** [jonkykong/SideMenu#270]
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

**Getting this warning:**

`SideMenu Warning: menuAddScreenEdgePanGesturesToPresent for the right side was called before menuRightNavigationController has been defined. The gesture will not work without a menu.`

**Note:** I am not setting side menu for the right side.

**Comment by jonkykong** [comment]
Then ignore the warning or call it only for the left menu.

**Comment by hemangshah** [comment]
But why it's giving me this warning this is more important then to ignore. I can't ignore a single warning because of the project I am working on. These small warnings create problem in future.

**Comment by jonkykong** [comment]
@hemangshah you need to read the README more carefully as well as investigate the code and problems first before opening issues. You have opened several issues and commented on several other issues in this repository which suggest to me that you prefer to open issues instead of investigating things yourself.

As I said, call the `menuAddScreenEdgePanGesturesToPresent` for the left side menu only and you will not get this warning any further.

**Comment by hemangshah** [comment]
Yeah, I will open up an issue as long as I couldn't find my self a solution in the demo itself. As this repo is having more than 1500 stars it's likely for my belief that, @jonkykong (you) will provide a great support for this component. For a good note, if someone will open an issue here instead of closing them directly, you should check and provide a solution for that then only people will think to pay you for your hard work for this component else **no one**!

**Comment by hemangshah** [comment]
For everyone else, 

**This is the code snippet to fix this:**

`SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view, forMenu: .left)`

**Comment by jonkykong** [comment]
@hemangshah with all due respect, you should **not** _expect_ any support from me, and try to resolve issues on your own whenever possible. I have spent my free time putting this library together, but that **does not** also require me to maintain it and provide support at all. It is a courtesy that I provide when I have time. I do not owe you or anyone else my time for something I am giving away for free.

You will not know this until you provide a popular library yourself, but ongoing support takes up a _lot_ of time and I'm not getting compensated for that. I guarantee you that no one will compensate me if I provide additional support; it's a nice idea but it just does not happen -- if you would like to be the first to prove me wrong, be my guest. This is why I close issues without responding with further detail, because there are an **endless** amount of these requests opened by people who don't bother to read or investigate things themselves. 

I want people to open up issues only when there is a real bug, and in this instance there was no bug. If you had taken a peek at the underlying code you would have discovered how to resolve this (faster) without opening an issue and waiting for me to respond.

**Comment by hemangshah** [comment]
I appreciate your comments and agrees with it !! @jonkykong

**Comment by hemangshah** [comment]
@jonkykong – How to remove a SideMenu completely, I am adding a comment in this task and not opening another Issue here 👍 I wish I will get an answer from you.

I have requirements to change the UI forcefully based on the language. I have two languages for my app. English and Arabic. So with case Arabic language, I have to show the SideMenu from Right to Left. I am able to set up the right navigation controller for SideMenu but it only works for two times then it is crashing. So I am thinking to remove it completely and then re-add it. Is there a way to remove it? I tried setting `nil` to menuLeft.. and menuRight.. properties but they don't work for me.

**Comment by hemangshah** [comment]
Yeah, I have tried checking and finding the real problem for few hours then I raised this comment. I still looking for if there's a way to remove SideMenu completely?

**Comment by jonkykong** [comment]
You need to investigate and provide more details:
* What happens when you set the menu to `nil`? How does it "not work"? What are the values of the properties _before_ and _after_ you set them? What line of code is preventing it from working the way you expect?
* What is the crash that occurs? What line of code is the crash occurring on? What action did you perform that causes the crash? Why does it work "two times" before crashing? What changed between the two working times and the time that it crashed?
