### ISSUE TITLE
UISideMenuNavigationControllerDelegate: delegate are necessary in specific cases

### ISSUE THREAD

**Issue by skrew** [jonkykong/SideMenu#280]
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [-] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
In some specific case (like mine, the controller are embedded in a container view), the UISideMenuNavigationControllerDelegate protocol don't works.

When debugging, `temporarySideMenuDelegate` contain the parentViewController, while i have the delegate functions in the embedded controller.

I understand why you have chosen this method but it don't fit in all situations.

Thanks

Edit:
I have added `open var customDelegate: UISideMenuNavigationControllerDelegate?`
and, in `findDelegate` function, added:
```
if (customDelegate != nil) {
    return customDelegate
}
```

who just works, but i don't know if you want a PR for this (you maybe have a better solution)

**Comment by jonkykong** [comment]
Hi @skrew, I think I understand your problem.

I designed it this way for simplicity, but admittedly it doesn't exactly follow the classic delegate paradigm (of explicitly setting the delegate to receive messages).

As a solution you could instead make your child view controller a delegate of your parent that receives these messages and pass them along. I'll keep this specific issue in mind for the future... but in general I've been designing everything in this library around making it easy for developers, particularly new developers so that I can minimize the amount of new open issues I have to deal with.
