### ISSUE TITLE
Adjust Navigation Bar height

### ISSUE THREAD

**Issue by bryantm1123** [jonkykong/SideMenu#281]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi JonkyKong,

Long-time user of SideMenu and big fan!

I'm working on a new project in Swift 4 and trying to increase the height of the navigation bar that shows in the side menu.

I've tried the following solutions from SO, using _both_ the SideMenuManager instance in my main view controller and the navigation bar exposed through the Side Menu navigation controller:
[https://stackoverflow.com/questions/40751366/how-can-i-change-height-of-navigation-bar-swift-3](https://stackoverflow.com/questions/40751366/how-can-i-change-height-of-navigation-bar-swift-3)
[https://stackoverflow.com/questions/46138245/how-to-change-navigationbar-height-in-ios-11](https://stackoverflow.com/questions/46138245/how-to-change-navigationbar-height-in-ios-11)

So far no luck. Just wondering if you've run across this before or if there is anything specific I should do with these implementations to make them work with SideMenu?

Thanks!
Matt

**Comment by jonkykong** [comment]
@bryantm1123 are you able to adjust the navigation bar height without using SideMenu in your project? If not, then your solution does not work. If so, then my guess would be that the layout logic for the navigation bar height is getting triggered when the menu is being displayed. Either way this is an uncommon request for me to support. Alternative solutions are to create a mock-navigation bar or to add one manually to the view instead of relying on the navigation controller.
