### ISSUE TITLE
Issue in SideMenu 3.1.2  UISideMenuNavigationController(coder: NSCoder)

### ISSUE THREAD

**Issue by joyalserrao** [jonkykong/SideMenu#285]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

After Update pods 3.1.2 i am facing following issue ,
UISideMenuNavigationController(coder: NSCoder) 
 before it was UISideMenuNavigationController(rootViewController: Vc). Please help me

**Comment by StDogbert** [comment]
@joyalserrao Add post_install script to your Podfile:
post_install do |installer|
    installer.pods_project.targets.each do |target|
      # puts "Target name: #{target.name}"
      if target.name == "SideMenu"
        puts "Updating #{target.name} SWIFT_ACTIVE_COMPILATION_CONDITIONS"
        target.build_configurations.each do |config|
          if config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] == nil 
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= ['$(inherited)']
          end
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] << 'STFU_SIDEMENU'
        end
      end
    end
end

If you look in UISideMenuNavigationController.swift file, you will find a comment from developer, explaining this STFU_SIDEMENU setting. 

I am kinda sure that should be removed or changed though. Its not convenient to pass compilation flags from main project to pods (if you are using cocoapods). Also I don't think its a good idea even if you can do it some easy way... Maybe some realtime checks and warnings to avoid described problems?

**Comment by sirioz** [comment]
3.1.2 introduced a breaking changes, while the versioning just suggested a simple bugfix.

**Comment by timbaev** [comment]
and in 3.1.2 in storyboard no item "Left side". I try change side from the code, but it is not work for me..

**Comment by jonkykong** [comment]
@joyalserrao this was intended as I had a lot of newbies creating blank menus and opening issues because they don't understand. I created the STFU_SIDEMENU flag to that this could be re-enabled for other developers. So... sorry for the frustration folks, but I'm apparently passing on this frustration to you :( I'm open to other suggestions aside from a compilation condition to accomplish this.

Why are you creating a `UISideMenuNavigationController` without a root controller? You will likely be setting a root view controller at some point so it shouldn't be too difficult to support this initializer, correct?

@sirioz can you elaborate further?

@timbaev LeftSide still appears in my projects. You may be doing something else wrong.

**Comment by oyalhi** [comment]
@jonkykong initializing with a root view controller gives error, as it is NOT available with version 3.1.2. UISideMenuNavigationController(rootViewController: Vc). You can NOT create WITH a root controller. It was available before.

**Comment by StDogbert** [comment]
@jonkykong You could add some check for content in root controller and print warnings with UPPERCASE if there is something wrong. 

Right now you kinda added some sort of "decent developer" captcha. I can understand the intention, but it will most likely hurt project in long run. I wouldn't even try to find the problem with framework if I didn't knew it was working before.

Like @oyalhi here, if someone doesn't want to read, they will still find a problem and raise some issues for you.

@oyalhi This was literally answered in first response to issue (if you are using cocoapods). If not - just add  STFU_SIDEMENU flag to SWIFT_ACTIVE_COMPILATION_CONDITIONS project setting.

**Comment by jonkykong** [comment]
@StDogbert this is in fact already done (without uppercase), and I still get open issues. Probably because there is already so much other debug content being generated that it gets pushed out of view. I'll consider adding an exception instead of the compilation conditions in the future based on the amount of support this generates.

@oyalhi you are in fact correct. In my initial testing of these changes, for whatever reason, I didn't encounter this issue. Trying it again now, I see it is a problem. I've fixed this in 3.1.3.

**Comment by kajensen** [comment]
I'd just like to voice my displeasure with this change. Its your library, you're responding to issues, you can do what you want- I get it.

But hacking up a podfile for this one library (as well as hacking up your codebase) because people are opening help issues doesn't make sense to me. I think you're going to anger more people (as evidenced by this thread- the most recent issue still 4 days after it was created) than you are helping(?).

**Comment by jonkykong** [comment]
@kajensen I appreciate your input and will keep it in mind.

While I understand the inconvenience of modifying your podfile, the changes to the library itself were minimal. I believe most of the frustration was actually the result of me not providing all the desired initializer overrides; not removing the default init. The other problems cited here I believe are unrelated (LeftSide not resolving).

I'll keep an eye on it over the coming days.
