### ISSUE TITLE
Menu is resized after presenting UIViewController

### ISSUE THREAD

**Issue by Nominalista** [jonkykong/SideMenu#291]
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

MenuView is changing width to full width of container after any UIViewController is presented (I mean after using method present). If we have (like in my case) UICollectionView inside MenuView, it resizes to full width of container, but never gets back to desired width (sizeForItemAt is called when UICollectionView gets full width, but then it's not called again).

**Comment by jonkykong** [comment]
@Nominalista you checked that this is reproducible in the demo project, but the demo project does not use UICollectionViews. If you have modified the demo project to include a simple collectionView that demonstrates this problem, then you should include that in this thread.

Otherwise, it's highly unlikely that this is an issue with SideMenu. You'll need to investigate when to appropriately resize your collectionView to lay out properly.

**Comment by Nominalista** [comment]
CollectionView was as an example. The issue is with resized menu view after presenting view controller which is reproducible in demo project.

**Comment by jonkykong** [comment]
@Nominalista I am unclear on what the problem is then. Please provide precise steps to reproduce in the demo project, and/or provide a modified project that demonstrates the issue.

**Comment by Nominalista** [comment]
First change segue kind to 'Present Modally' for PresentedViewController and add button for dismissing this controller.

Now let's take a look on UISideMenuNavigationController. 

Add two breakpoints - one in viewWillAppear and second in viewDidAppear. Select one of the table view cells from menu inside the example app in order to present PresentedViewController. Now if you dismiss this controller, the debugger will stop on viewWillAppear method. Check view.bounds.width and you will notice that it is equal to menuWidth from SideMenuManager. But when you run the debugger and it will stop on viewDidAppear you will see that view.bounds.width is equal to appScreen.width. If you open menu again, view.bounds will restore to desired width, but in case of subviews like UICollectionView it creates many issues. Can you explain why it's happening at least?

**Comment by jonkykong** [comment]
The width is likely getting changed as part of an internal layout pass rather than anything my code is doing. I'd have to debug in-depth to figure out when and why. You're the first developer to mention this issue... this leads me to believe it hasn't been a complication for others. I use SideMenu in many of my projects and have no layout troubles.

Is there a reason you can't handle layout changes in `viewDidLayoutSubviews`?

**Comment by Nominalista** [comment]
I'm just reloading the UICollectionView in viewWillAppear, so the cells are resized properly, but I created this issue rather to ask if this is accurate behavior of menu. 

I establish that most of the developers won't have this problem, so I guess the discussion is finished. Thanks for answers.
