### ISSUE TITLE
左边菜单中，不能使用左右手势    - the menu on the left, can't use hand gestures

### ISSUE THREAD

**Issue by renwfy** [jonkykong/SideMenu#3]
左边菜单中，不能使用左滑右滑手势，。左边菜单中tableview不能使用左滑删除

the menu on the left, can't use hand gestures  ,.   tableview in leftMenu can't use left slide to delete

**Comment by jonkykong** [comment]
Hi @renwfy, thanks for opening this issue.

My initial design for this control was to allow easy navigation. Slide to delete is related more to managing some data, which should be done on a main screen and not in a side menu. I think most people would expect gestures to dismiss the menu instead of swiping to delete. Given all of this, I think this behavior is by design and not an issue.

If you feel that your scenario is important to support, please feel free to modify the code to do so.

**Comment by gunnarblom** [comment]
@jonkykong enabling swipe to delete in the right menu makes sense to me. And it shouldn't interfere with the hide menu pan movement as they are opposite directions. But I can't seem to understand how I would tweak it to make it work. Now swipe-to-delete works if I swipe really fast, but not normal speed :)

Any idea what is happening so I can investigate further how to enable it?

Thanks!

**Comment by jonkykong** [comment]
@gunnarblom you'll need to read up on gestures and how to require one to fail for the other one to work.
