### ISSUE TITLE
when useing "QLPreviewController" with SideMenu...

### ISSUE THREAD

**Issue by pangpingfei** [jonkykong/SideMenu#32]
it can't touch right part to shutdown SideMenu.

当使用QLPreviewController放在我的Controller里时，拉出SideMenu，不能点击右侧遮罩处关闭SideMenu。因为能直接操作QLPreviewController。

**Comment by jonkykong** [comment]
Hi @pangpingfei,

It sounds like you are running into problems with using gestures to dismiss SideMenu because your presenting screen (a QLPreviewController) has gestures as well.

There are many possible screens that can support gestures that may conflict with SideMenu. I cannot account for every possibility in SideMenu. It is up to developers to figure out the right experience and code for it when this happens, so that SideMenu or the main screen recognize gestures as the developer expects.

To solve this yourself, try:

- Not displaying SideMenu when the QLPreviewController is shown.
- Subclassing UISideMenuNavigationController to get gestures to work correctly with your screen.
- Subclassing QLPreviewController to get gestures to work correctly with your screen.

Hope this helps.

**Comment by pangpingfei** [comment]
@jonkykong Got it, Thanks!
