### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x7fcfee790c90>.

### ISSUE THREAD

**Issue by hr147** [jonkykong/SideMenu#322]
<img width="773" alt="sidebar" src="https://user-images.githubusercontent.com/15008942/35662550-889e58fa-073a-11e8-8d3c-b6150720a12f.png">
<img width="495" alt="tabbar" src="https://user-images.githubusercontent.com/15008942/35662552-89100cc0-073a-11e8-9754-42c2f3ca974e.png">

Tabbar is my Main UI and when ever i select any controller from sidebar it push on selected tab controller but logged transition unbalanced warning 

do u still need detail i have attached screen please try at your end. and do let me know. Thanks

**Comment by hr147** [comment]
Please dont close this ticket before solving my problem Thanks

**Comment by jonkykong** [comment]
@hr147 you are not following the instructions for opening an issue on this repo (completing the checklist), nor providing enough detail (such as the example project itself so I don't have to make one), so your issue is being closed. If you follow the guidelines you will have better success getting help.
