### ISSUE TITLE
BackgroundImage Fit 

### ISSUE THREAD

**Issue by lkevin029** [jonkykong/SideMenu#34]
SideMenuManager.menuAnimationBackgroundColor = UIColor(patternImage: UIImage(named: "stars")!)

how to make it fit on the screen?

**Comment by jonkykong** [comment]
Hi @lkevin029. Creating a color from an image will tile it across the background. SideMenu doesn't currently support setting a single image to be stretched or filled as the background. This was a design choice because doing so because stretched images can look bad, and aspect fill/fit can have undesirable results too.

There are a few ways you can do this: you can dynamically size the image you want before setting it as the background, or you can put a background in your side menu view controllers themselves.
