### ISSUE TITLE
Provide example of how to navigate from a side menu

### ISSUE THREAD

**Issue by emadd** [jonkykong/SideMenu#391]
Looks like the author of this library is intentionally vague in hopes of getting donations.  Neither the REAME or the example project provide an example of how to actually navigate from a side menu.

**Comment by jonkykong** [comment]
@emadd You've insinuated I'm being misleading in the hope of tricking people into donating money to me.

I've written an entire open source library for **free** on **my own time**. If it's not meeting your needs, you're welcome to use something else or **write your own**. It's tasteless to attack the creator of something that's being given to you for free because you want even more or you have a problem.

To your main point: both the README _and_ the example project illustrate exactly what you're asking for. Please read carefully.

If you open any other disrespectful issues then I have no issue blocking you from this repo.
