### ISSUE TITLE
viewDidDisappear not called on MainViewController, when presenting SideMenu by code

### ISSUE THREAD

**Issue by ichina** [jonkykong/SideMenu#394]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

There is different behaviour of presenting SideMenu via Storyboard and via code:
I tried to present SideMenu by calling: 
`present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)`
SideMenu appeared successful, but MainViewController did not notified 'bout disappearing, viewWillDisappear and viewDidDisappear not called.
Its works fine on presenting Side menu via Storyboard with Segues

**Comment by jonkykong** [comment]
I have been able to reproduce your problem.

Unfortunately, this library has been out for a long time and you're the first one to request a fix, so I'm not inclined to dedicate my time for a fix. You are welcome to investigate a solution and propose it to the library.

Using breakpoints, there is no specific SideMenu code that is calling appearance events. It is all happening (inconsistently) as part of the transition APIs built by Apple.

**Comment by lukas1** [comment]
I think I may have some useful feedback regarding this issue.

It all comes down to this line in `SideMenuManager` :
`forMenu.modalPresentationStyle = .overFullScreen`

Modal Presentation style decides whether system callbacks such as `viewWillDisappear` will be called on presenting view controller.

Problem is, that when you're using segues, it overwrites the modal presentation style in `prepare(forSegue:)` the `modalPresentationStyle` is set to default value, which is `fullScreen`. `fullScreen` causes `viewWillDisappear` to be called on presenting View Controller.

Maybe this library could provide a custom segue, instead of using the default present segue, but I'm not sure this is what the author of this library intends.. It might add some overhead to setup of the menu.

Instead, what you can do is, in your case since you want to present the menu manually from code using `present(viewController:)`, prior to actually presenting the viewcontroller, change it's `modalPresentationStyle` to `.fullscreen` like this:
`SideMenuManager.default.menuLeftNavigationController.modalPresentationStyle = .fullScreen`


I personally have run into the OPPOSITE issue. I'm opening the menu via storyboard segue, but since the menu does not cover the whole screen, I don't want the view will appear and view will disappear methods to be called on my presenting view controller.

Therefore, what I personally did for my project is, that in `prepare(forSegue:)` method I set the modalPresentationStyle to `.overFullScreen` (as in the code of the library).

Maybe it would be nice to add this information to documentation or somewhere, so that other people don't waste their time figuring out issues related to `viewWillDisappear` etc being called/not called, due to the modalPresentationStyle.

I hope that helps.

**Comment by ichina** [comment]
@lukas1 you absolutely right
