### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by richardtop** [jonkykong/SideMenu#496]
The SideMenu v 6.0.0 minimum deployment target is iOS 10.x.
Is there a specific reason for it, or this SideMenu version can be run successfully on iOS 9?
What APIs are unavailable on the iOS 9 so that the library cannot be used?

**Comment by jonkykong** [comment]
It was upped for two reasons:
1. To be able to move on from an issue where changing the status bar appearance would lock the transition that was fixed in 9.3
2. Natural progression towards adopted versions. Currently, anything below iOS 11 sits at around ~5% of the market.

That said you should be able to change the minimum version in a private fork or rely on an older version of SideMenu for your project.

**Comment by richardtop** [comment]
Got it, thank you for the feedback!
