### ISSUE TITLE
App Crashing on updating from xcode 10 - xcode 11

### ISSUE THREAD

**Issue by shujavf** [jonkykong/SideMenu#545]
App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead

**Comment by chocolatesoup** [comment]
Seems to be the same issue:
https://github.com/kukushi/SideMenu/issues/67

**Comment by adriaros** [comment]
I had the same error: "App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead"

The problem is that uploading Xcode 11 and iOS 13 you cannot use UIApplication.shared.value(forKey: "statusBar").

**Comment by jonkykong** [comment]
`6.4.0`

**Comment by rau4o** [comment]
how to solve this problem ???Help please 👍
