### ISSUE TITLE
dismissOnPresent on iOS 13

### ISSUE THREAD

**Issue by leo150** [jonkykong/SideMenu#558]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When modally presenting a controller from the side menu on iOS 13 the menu doesn't dismiss. The problem itself is because of iOS 13 `modalPresentationStyle` changes:

> Defaults to UIModalPresentationAutomatic on iOS starting in iOS 13.0, and UIModalPresentationFullScreen on previous versions.

As result, `viewWillDisappear` of `SideMenuNavigationController` isn't called, when presenting a controller with default presentation style. So `dismissOnPresent` flag isn't handled. 

**To Reproduce**
1. Open sample project
2. Open right menu
3. Click on any row
4. Controller is presented, but the side menu isn't dismissed

**Additional context**
This could be fixed by 
```
myPresentedController.modalPresentationStyle = .fullScreen
```

Is it more correct to handle modal presentation in the different way by SideMenu or always keep presentation style as `fullScreen`?

**Comment by jonkykong** [comment]
This has always been SideMenu's behavior for any modal presentation that doesn't completely hide the controller it was presented from; specifically `viewWillDisappear` etc aren't called under those conditions. It wouldn't be right for SideMenu to override the presentation of a controller by forcing it to be `.fullScreen`, this is really a developer choice to make.

For now this seems to make sense since you aren't hiding the screen you left, so there's still context about what you left behind. I could be persuaded to change it, but right now it's not on my priority list.
