### ISSUE TITLE
SideMenu will not dismiss after selecting menu item

### ISSUE THREAD

**Issue by goransleko** [jonkykong/SideMenu#635]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When the SideMenu is swiped open, and an item on the menu is tapped, the menu UI will not close. This is causing issues since we have unwind segues, because after performing unwind segue the menu closes, and trying to open it again results in crash.
I think this is the similar bug as in issue #520. 

**To Reproduce**

1. Open the menu
2. Tap a menu item

**Expected behavior**
I expect the menu to automatically dismiss after selecting item and performing segue to another storyboard.

**Additional context**
I have created a simple project which shows the issue:
https://github.com/goransleko/MenuIssue

**Comment by jonkykong** [comment]
@goransleko thank you for taking the time to put together a demo project.

This behavior _also_ occurs in the demo project, and is by design, currently. View controller lifecycle events are not called when the modal presentation style is `automatic` or `pageSheet`; e.g. SideMenu's `viewWillDisappear` is not called (which it uses to hide itself) since it remains visible in the view hierarchy behind the presented view controller.

Unfortunately, without these life cycle events being called, it is not easy to solve this using Apple's APIs from within `SideMenuNavigationController`. Navigation controllers have no awareness of their view controllers presenting other view controllers, or calling segues, meaning it requires code to be added outside of SideMenu anyway. At best, you would still have to call a private SideMenu function that visually dismisses SideMenu as your new view controller presents. One of the goals with this repo is to avoid the need for specialized code on multiple different controllers, which is why it behaves the way it does now.

You can change this behavior by:
1. Changing the modalPresentationStyle of your presented view controller to `fullScreen`.
2. Programmatically dismissing SideMenu before your new view controller is presented. You will have to wait for SideMenu to fully dismiss before your view controller is presented, which may be an undesirable wait.

If you see an alternative solution, please reply with that suggestion.

**Comment by goransleko** [comment]
Oh ok I see, I have just used solution 2 and it seems to work ok.

`@IBAction func btnTest(_ sender: Any) {
        weak var pvc = self.presentingViewController
        self.dismiss(animated: false, completion: {
            pvc!.performSegue(withIdentifier: "segueLogin", sender: nil)
        })
    }`

**Comment by jonkykong** [comment]
Minor edits, for safety:
> ```swift
> @IBAction func btnTest(_ sender: Any) {
>         weak var pvc = self.presentingViewController
>         self.dismiss(animated: false, completion: {
>             pvc?.performSegue(withIdentifier: "segueLogin", sender: nil)
>         })
> }
> ```
