### ISSUE TITLE
example project seems to not work properly as expeted?!

### ISSUE THREAD

**Issue by flandy84** [jonkykong/SideMenu#90]
just found your nice side-menu library. loosks very nice on the gifs.
I build the example project and in runs on ios 10/9 devices and Simulator, but when i try to present left or right menu i stay in this screen (no way of return).

https://dl.dropboxusercontent.com/u/12083655/Bildschirmfoto%202016-10-25%20um%2011.00.25.png

what's going wrong here? 

PS: for reproducing-purposes i placed your example project here (i removed cocoapods dependency for independant build): https://dl.dropboxusercontent.com/u/12083655/SideMenu-master%202.zip

**Comment by jonkykong** [comment]
@flandy84 The example project from my original source works as expected.

You need to read the logging in Xcode more thoroughly and investigate the root cause on your own before asking for help. There are plenty of potential root causes for what's happening, none of which have anything to do with SideMenu's code. There are long posts on Stackoverflow about this issue.

#58

**Comment by flandy84** [comment]
@jonkykong ok. removed "Module" reference from storyboard-Viewcontrollers to fix the issue.
should be a build-time error when compiling story-board files (imho), not a runtime-issue. (apple/xcode/IB workflow)
thx for advice
